### ISSUE TITLE
NBest-corpus

### ISSUE THREAD

**Issue by psmit** [laurensw75/kaldi_egs_CGN#1]
Hi,

I have been looking to obtain the Nbest corpus to evaluate my own CGN-recipe. I notice in your dataprep that your development set is created using a file named "nbest". Is the Nbest development set a subset of CGN?

Do you know a place I could obtain the evaluation part of that corpus? TST-Centrale does offer it anymore...

Regards,

Peter Smit
(peter.smit@aalto.fi)

**Comment by laurensw75** [comment]
Hi Peter,

When we participated in the NBest benchmark, the development set was indeed
a part of CGN. As it's been a while, I cannot be 100% sure which parts of
CGN were in fact development set, but the list I used are the most likely
ones.
I am also not sure where to get the NBest corpus, but perhaps David van
Leeuwen <d.vanleeuwen@let.ru.nl> can tell you more about this. Also, I
think Spex was involved, so Henk van den Heuvel <h.vandenheuvel@let.ru.nl>
would be another option. If they have no objections to me sharing it, if
needed, I would be happy to provide you with what I have.

In the mean time, I am really interested in your CGN-recipe :-)

Best,

Laurens
